/**
 * generateFont.js
 * Run once to (re)generate khmerFontBase64.ts from KhmerOS.ttf.
 *
 * Usage:
 *   node lib/generateFont.js
 *
 * This encodes the KhmerOS font as a base64 string so khmerShaper.ts
 * can use it as a fallback when the network fetch of /KhmerOS.ttf fails
 * (e.g. during SSR, offline builds, or Vercel edge functions).
 */

const fs   = require('fs');
const path = require('path');

const fontPath   = path.join(__dirname, '..', 'public', 'KhmerOS.ttf');
const outputPath = path.join(__dirname, 'khmerFontBase64.ts');

if (!fs.existsSync(fontPath)) {
    console.error(`ERROR: Font not found at ${fontPath}`);
    console.error('Make sure KhmerOS.ttf is in the /public directory.');
    process.exit(1);
}

const b64      = fs.readFileSync(fontPath).toString('base64');
const fileSize = fs.statSync(fontPath).size;

fs.writeFileSync(
    outputPath,
    `// Auto-generated by lib/generateFont.js — do not edit manually.\n` +
    `// Source: public/KhmerOS.ttf (${(fileSize / 1024).toFixed(1)} KB)\n` +
    `export const khmerFontBase64 = "${b64}";\n`
);

console.log('✅  khmerFontBase64.ts updated with KhmerOS font.');
console.log(`    Source : ${fontPath}`);
console.log(`    Size   : ${fileSize.toLocaleString()} bytes (${(fileSize / 1024).toFixed(1)} KB)`);
console.log(`    Output : ${outputPath}`);
