'use client';

import React from 'react';
import ReactDOM from 'react-dom';
import { AuthProvider } from '@/contexts/AuthContext';
import { DataProvider } from '@/contexts/DataContext';
import { B2BProvider } from '@/contexts/B2BContext';
import { NavigationProvider } from '@/contexts/NavigationContext';
import { NotificationProvider } from '@/contexts/NotificationContext';
import { ConnectivityProvider } from '@/contexts/ConnectivityContext';
import { WindowManagerProvider } from '@/contexts/WindowManagerContext';
import WindowManagerRoot from '@/components/windows/WindowManagerRoot';
import ThemeBackground from '@/components/theme/ThemeBackground';

// Polyfill findDOMNode for compatibility with legacy libraries like react-quill
// in environments where it might be missing (React 19+ or specific Next.js builds)
if (typeof window !== 'undefined' && !(ReactDOM as any).findDOMNode) {
    (ReactDOM as any).findDOMNode = (instance: any) => {
        if (!instance) return null;
        if (instance instanceof HTMLElement) return instance;
        return (instance as any).getDOMNode ? (instance as any).getDOMNode() : null;
    };
}

// ---- Inline Theme Provider (no extra file needed) ----
export type ThemeMode =
    | 'light' | 'dark' | 'claude'
    | 'midnight' | 'paper' | 'cyberpunk' | 'retrowave' | 'forest' | 'ocean'
    | 'ume' | 'copper' | 'terminal' | 'organs' | 'lavender' | 'gpt' | 'cute';

// Swatch-preview colors for the theme picker, as "H S% L%" HSL triples
// matching each theme's --background/--card/--foreground/--primary defaults
// (the user's accent override is layered on top of `primary` at runtime).
// The 13 odysseus-derived palettes were generated by scripts/gen-themes.mjs.
export type ThemeMeta = {
    id: ThemeMode;
    label: string;
    dark: boolean;
    bg: string;
    card: string;
    fg: string;
    primary: string;
};

export const THEME_META: ThemeMeta[] = [
    { id: 'light', label: 'Light', dark: false, bg: '0 0% 100%', card: '0 0% 100%', fg: '222.2 84% 4.9%', primary: '215 100% 34%' },
    { id: 'dark', label: 'Original', dark: true, bg: '40 3% 15%', card: '40 4% 19%', fg: '40 10% 91%', primary: '215 85% 63%' },
    { id: 'claude', label: 'Claude', dark: true, bg: '40 3% 15%', card: '40 4% 19%', fg: '40 10% 91%', primary: '15 54% 51%' },
    { id: 'midnight', label: 'Midnight', dark: true, bg: '216 27.8% 7.1%', card: '215 21.4% 11%', fg: '210 17.4% 82%', primary: '3 92.6% 62.9%' },
    { id: 'paper', label: 'Paper', dark: false, bg: '36 33.3% 97.1%', card: '0 0% 100%', fg: '24 4.4% 22.2%', primary: '48 51.5% 53.1%' },
    { id: 'cyberpunk', label: 'Cyberpunk', dark: true, bg: '240 20% 4.9%', card: '252 23.8% 8.2%', fg: '183 97.5% 52.4%', primary: '291 95.9% 61.8%' },
    { id: 'retrowave', label: 'Retrowave', dark: true, bg: '240 27.8% 14.1%', card: '224 47.6% 16.5%', fg: '350 78.8% 59.2%', primary: '350 78.8% 59.2%' },
    { id: 'forest', label: 'Forest', dark: true, bg: '120 21.7% 13.5%', card: '120 28.6% 11%', fg: '113 37.8% 73.5%', primary: '111 33.3% 58.2%' },
    { id: 'ocean', label: 'Ocean', dark: true, bg: '213 60% 10.8%', card: '214 58.1% 8.4%', fg: '197 100% 69.6%', primary: '208 98.9% 65.3%' },
    { id: 'ume', label: 'Ume', dark: true, bg: '291 26% 14.3%', card: '290 23.1% 10.2%', fg: '316 71.8% 86.1%', primary: '337 81% 79.4%' },
    { id: 'copper', label: 'Copper', dark: true, bg: '20 27.3% 8.6%', card: '30 33.3% 5.9%', fg: '30 61.7% 76.5%', primary: '18 60.9% 56.9%' },
    { id: 'terminal', label: 'Terminal', dark: true, bg: '0 0% 0%', card: '0 0% 3.9%', fg: '135 100% 50%', primary: '135 100% 50%' },
    { id: 'organs', label: 'Organs', dark: true, bg: '340 42.9% 2.7%', card: '351 44.8% 5.7%', fg: '38 54.9% 86.1%', primary: '354 60% 49%' },
    { id: 'lavender', label: 'Lavender', dark: false, bg: '270 41.7% 95.3%', card: '262 100% 98.4%', fg: '257 20.9% 26.3%', primary: '269 48.2% 61.4%' },
    { id: 'gpt', label: 'GPT', dark: true, bg: '0 0% 12.9%', card: '0 0% 9%', fg: '0 0% 92.5%', primary: '0 0% 58%' },
    { id: 'cute', label: 'Cute', dark: false, bg: '340 100% 97.1%', card: '343 100% 98.6%', fg: '338 57.4% 60.4%', primary: '340 100% 71%' },
];

// Theme ids that map to a dedicated `.theme-<id>` CSS class (everything
// beyond the original light/dark/claude trio, which use bare :root/.dark/.claude).
const NEW_THEME_IDS: ThemeMode[] = THEME_META.map(t => t.id).filter(id => id !== 'light' && id !== 'dark' && id !== 'claude');

// Ambient animated-background patterns, ported from odysseus. `effectColor`
// overrides the default (the theme's --foreground), `intensity` scales
// particle density/opacity (0..1, default 1).
export type BgPattern =
    | 'none' | 'dots' | 'synapse' | 'rain' | 'constellations'
    | 'perlin-flow' | 'petals' | 'sparkles' | 'embers';

export type ThemeBackground = {
    pattern: BgPattern;
    effectColor?: string;
    intensity?: number;
};

export const THEME_BACKGROUNDS: Record<ThemeMode, ThemeBackground> = {
    light: { pattern: 'dots' },
    dark: { pattern: 'none' },
    claude: { pattern: 'none' },
    midnight: { pattern: 'rain', effectColor: '#ffffff', intensity: 0.5 },
    paper: { pattern: 'dots' },
    cyberpunk: { pattern: 'synapse' },
    retrowave: { pattern: 'embers' },
    forest: { pattern: 'petals' },
    ocean: { pattern: 'constellations' },
    ume: { pattern: 'petals', effectColor: '#f5a0c0' },
    copper: { pattern: 'none' },
    terminal: { pattern: 'perlin-flow', intensity: 0.8 },
    organs: { pattern: 'rain', effectColor: '#451616', intensity: 0.65 },
    lavender: { pattern: 'none' },
    gpt: { pattern: 'none' },
    cute: { pattern: 'sparkles', effectColor: '#ff8cb8' },
};

// User-picked accent color, stored as the H/S components of --primary's
// "H S% L%" triple — L stays theme-driven so contrast keeps working across
// every theme. null means "use the active theme's default accent".
export type AccentColor = { h: number; s: number } | null;

const ThemeContext = React.createContext<{
    theme: ThemeMode;
    isDark: boolean;
    setTheme: (theme: ThemeMode) => void;
    accent: AccentColor;
    setAccent: (accent: AccentColor) => void;
}>({ theme: 'light', isDark: false, setTheme: () => {}, accent: null, setAccent: () => {} });

export const useTheme = () => React.useContext(ThemeContext);

// Re-registers the ECharts theme (which reads --primary etc.) and forces all
// live chart instances to redraw. Needed after either the theme class or the
// accent CSS variables change.
function reapplyChartTheme() {
    import('echarts').then(echarts => {
        import('../charts/echartsTheme').then(({ buildLimperialTheme }) => {
            echarts.registerTheme('limperial', buildLimperialTheme());
            // Trigger resize on all live ECharts instances so they re-apply
            // the new theme. A resize call causes ECharts to re-render fully.
            try {
                (echarts as any).getInstanceByDom &&
                document.querySelectorAll('[_echarts_instance_]').forEach((el) => {
                    const instance = (echarts as any).getInstanceByDom(el as HTMLElement);
                    if (instance && !instance.isDisposed()) {
                        instance.resize();
                    }
                });
            } catch (_e) {
                // Silently ignore — some chart instances may not exist yet
            }
        });
    });
}

function ThemeProvider({ children }: { children: React.ReactNode }) {
    const [theme, setThemeState] = React.useState<ThemeMode>(() => {
        if (typeof window === 'undefined') return 'light';
        const saved = localStorage.getItem('limperial-theme');
        if (saved && THEME_META.some(t => t.id === saved)) return saved as ThemeMode;
        return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
    });

    React.useEffect(() => {
        const root = document.documentElement;
        const meta = THEME_META.find(t => t.id === theme);

        if (meta?.dark) {
            root.classList.add('dark');
            root.classList.remove('b2b-dark');
        } else {
            root.classList.remove('dark');
        }

        root.classList.remove('claude');
        NEW_THEME_IDS.forEach(id => root.classList.remove(`theme-${id}`));

        if (theme === 'claude') {
            root.classList.add('claude');
        } else if (NEW_THEME_IDS.includes(theme)) {
            root.classList.add(`theme-${theme}`);
        }

        const bg = THEME_BACKGROUNDS[theme];
        if (bg.effectColor) {
            root.style.setProperty('--bg-effect-color', bg.effectColor);
        } else {
            root.style.removeProperty('--bg-effect-color');
        }
        root.style.setProperty('--bg-effect-intensity', String(bg.intensity ?? 1));

        localStorage.setItem('limperial-theme', theme);

        reapplyChartTheme();
    }, [theme]);

    const [accent, setAccentState] = React.useState<AccentColor>(() => {
        if (typeof window === 'undefined') return null;
        try {
            const saved = localStorage.getItem('limperial-accent');
            if (!saved) return null;
            const parsed = JSON.parse(saved);
            if (typeof parsed?.h === 'number' && typeof parsed?.s === 'number') return parsed;
        } catch (_e) {
            // Ignore malformed localStorage value
        }
        return null;
    });

    React.useEffect(() => {
        const root = document.documentElement;
        if (accent) {
            root.style.setProperty('--accent-h', String(accent.h));
            root.style.setProperty('--accent-s', `${accent.s}%`);
            localStorage.setItem('limperial-accent', JSON.stringify(accent));
        } else {
            root.style.removeProperty('--accent-h');
            root.style.removeProperty('--accent-s');
            localStorage.removeItem('limperial-accent');
        }

        reapplyChartTheme();
    }, [accent]);

    const setAccent = React.useCallback((next: AccentColor) => setAccentState(next), []);

    const setTheme = React.useCallback((next: ThemeMode) => setThemeState(next), []);

    const isDark = THEME_META.find(t => t.id === theme)?.dark ?? false;

    return (
        <ThemeContext.Provider value={{ theme, isDark, setTheme, accent, setAccent }}>
            <ThemeBackground />
            {children}
        </ThemeContext.Provider>
    );
}
// -------------------------------------------------------

export default function AppProviders({ children }: { children: React.ReactNode }) {
    return (
        <ThemeProvider>
            <AuthProvider>
                <B2BProvider>
                    <DataProvider>
                        <NavigationProvider>
                            <NotificationProvider>
                                <ConnectivityProvider>
                                    <WindowManagerProvider>
                                        {children}
                                        <WindowManagerRoot />
                                    </WindowManagerProvider>
                                </ConnectivityProvider>
                            </NotificationProvider>
                        </NavigationProvider>
                    </DataProvider>
                </B2BProvider>
            </AuthProvider>
        </ThemeProvider>
    );
}
